name: monitor-pipeline

on:
  schedule:
    - cron: '0 0 * * *' # pipeline will run every day at midnight; https://crontab.guru/#0_0_*_*_*

  workflow_dispatch:

jobs:

  monitor_pipeline:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync

      - name: Install DVC
        uses: iterative/setup-dvc@v1

      - name: Create credentials.json
        env:
          GDRIVE_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_CREDENTIALS }}
        run: echo $GDRIVE_SERVICE_ACCOUNT_CREDENTIALS > credentials.json

      - name: Configure DVC
        run: dvc remote modify gdrive --local gdrive_service_account_json_file_path credentials.json

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Execute pipeline
        run: make monitor_pipeline

      - name: Check for changes
        id: dvc-check
        run: dvc status --quiet || echo "CHANGES=true" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.CHANGES == 'true'
        run: make update_artifacts

      - name: Clean up repo
        run: |
          make clean
          rm -rf artifacts logs
